repos:
  - repo: git@github.com:psf/black.git
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.1.2
    hooks:
      - id: flake8
  - repo: git@github.com:PyCQA/isort.git
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
